### ISSUE TITLE
Error connecting to immudb from Java SDK

### ISSUE THREAD

**Issue by vishalbatra** [codenotary/immudb4j#9]
Environment/ Setup:
- immudb4j V 0.1.8 and Java 13
- immudb docker container on Mac

Getting the following error when connecting to  immudb from Java program:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/vishalsinghbatra/.m2/repository/io/netty/netty-common/4.1.11.Final/netty-common-4.1.11.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Oct 23, 2020 12:00:52 AM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<1>: (localhost:3322)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalArgumentException: gracefulShutdownTimeoutMillis: -1 (expected: >= 0)
at io.netty.handler.codec.http2.Http2ConnectionHandler.gracefulShutdownTimeoutMillis(Http2ConnectionHandler.java:109)
at io.grpc.netty.AbstractNettyHandler.<init>(AbstractNettyHandler.java:53)
at io.grpc.netty.NettyClientHandler.<init>(NettyClientHandler.java:247)
at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:223)
at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:152)
at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:218)
at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:254)
at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65)
at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:196)
at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1382)
at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:325)
at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:227)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)

io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
at io.codenotary.immudb.ImmuServiceGrpc$ImmuServiceBlockingStub.login(ImmuServiceGrpc.java:2612)
at io.codenotary.immudb4j.ImmuClient.login(ImmuClient.java:164)
at com.fc.util.io.immudb.ImmuDBUtil.connectImmuDB(ImmuDBUtil.java:54)
at com.fc.util.io.immudb.ImmuDBUtil.submit(ImmuDBUtil.java:23)
at com.fc.util.io.immudb.ImmuDBUtil.main(ImmuDBUtil.java:67)
Caused by: java.lang.IllegalArgumentException: gracefulShutdownTimeoutMillis: -1 (expected: >= 0)
at io.netty.handler.codec.http2.Http2ConnectionHandler.gracefulShutdownTimeoutMillis(Http2ConnectionHandler.java:109)
at io.grpc.netty.AbstractNettyHandler.<init>(AbstractNettyHandler.java:53)
at io.grpc.netty.NettyClientHandler.<init>(NettyClientHandler.java:247)
at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:223)
at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:152)
at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:218)
at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:254)
at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65)
at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:196)
at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1382)
at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:325)
at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:227)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
at io.codenotary.immudb.ImmuServiceGrpc$ImmuServiceBlockingStub.currentRoot(ImmuServiceGrpc.java:2731)
at io.codenotary.immudb4j.ImmuClient.root(ImmuClient.java:176)
at io.codenotary.immudb4j.ImmuClient.safeGet(ImmuClient.java:241)
at io.codenotary.immudb4j.ImmuClient.safeGet(ImmuClient.java:236)
at com.fc.util.io.immudb.ImmuDBUtil.query(ImmuDBUtil.java:38)
at com.fc.util.io.immudb.ImmuDBUtil.main(ImmuDBUtil.java:69)
Caused by: java.lang.IllegalArgumentException: gracefulShutdownTimeoutMillis: -1 (expected: >= 0)
at io.netty.handler.codec.http2.Http2ConnectionHandler.gracefulShutdownTimeoutMillis(Http2ConnectionHandler.java:109)
at io.grpc.netty.AbstractNettyHandler.<init>(AbstractNettyHandler.java:53)
at io.grpc.netty.NettyClientHandler.<init>(NettyClientHandler.java:247)
at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:223)
at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:152)
at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:218)
at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:254)
at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65)
at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:196)
at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1382)
at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:325)
at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:227)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by Giako** [comment]
Hi @vishalbatra, immudb4j supports the latest LTS JDK (version 11).

Could you confirm this bug is also affecting you on the 11 JDK, e.g. the AdoptOpenJdk distribution from [here](https://adoptopenjdk.net/)?

Do you get any issues with the immudb4j [Hello Immutable World](https://github.com/codenotary/immudb-client-examples/tree/master/java)?

**Comment by devisions** [comment]
Closing it due to inactivity.
